name: $(Build.SourceBranch)
trigger: none
appendCommitMessageToRunName: false

pool:
  vmImage: ubuntu-latest

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'az version --output table'
    pwsh: true
  displayName: 'Az Cli version before modifing'
  condition: always()

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo apt-get update
      sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
      sudo mkdir -p /etc/apt/keyrings
      curl -sLS https://packages.microsoft.com/keys/microsoft.asc |
          gpg --dearmor |
          sudo tee /etc/apt/keyrings/microsoft.gpg > /dev/null
      sudo chmod go+r /etc/apt/keyrings/microsoft.gpg
      AZ_DIST=$(lsb_release -cs)
      echo "deb [arch=`dpkg --print-architecture` signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ $AZ_DIST main" |
          sudo tee /etc/apt/sources.list.d/azure-cli.list
      AZ_VER=2.52.0
      sudo apt-get update
      sudo apt-get install -y azure-cli=$AZ_VER-1~$AZ_DIST --allow-downgrades
      az --version
  displayName: "Remove Az Cli 2.53 and install Az CLI 2.52"


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'az version --output table'
    pwsh: true
  displayName: 'Az Cli version After modifing'
  condition: always()
  enabled: true


