name: SecondPipeline 

trigger: none

# this pipeline will be triggered by another pipeline
resources:
  pipelines:
  - pipeline: previous-pipeline-trigger   # Name of the pipeline resource
    source: First-Pipeline-yaml # Name of the pipeline referenced by the pipeline resource
    project: test # Required only if the source pipeline is in another project
    trigger: # enable the trigger
     branches:
      include:
        - master
     tags: 
      - Verified
      - Signed
            
pool:
  vmImage: ubuntu-latest

steps:
  - script: echo This pipeline was set to be triggered after first pipeline completes.